services:
  postgres:
    image: postgres:16.1-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: FinancialDB
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - local-network

networks:
  local-network:
    driver: bridge



