services:
  postgres:
    image: postgres:16.1-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: FinancialDB
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - local-network

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    ports:
      - "9000:9000"
    networks:
      - local-network
    depends_on:
      - postgres

networks:
  local-network:
    driver: bridge



