spring:
  application:
    name: app
  datasource:
    url: jdbc:postgresql://localhost:5432/FinancialDB
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 3000
